// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var InvalidResponseCode = Caml_exceptions.create("TestSuite-Resting.HttpResponseCode.InvalidResponseCode");

function tryCreate(code) {
  var match = +(code >= 100 && code <= 500);
  if (match !== 0) {
    return /* Some */[/* HttpResponseCode */[code]];
  } else {
    return /* None */0;
  }
}

function create(code) {
  var match = +(code >= 100 && code <= 500);
  if (match !== 0) {
    return /* HttpResponseCode */[code];
  } else {
    throw [
          InvalidResponseCode,
          code
        ];
  }
}

var HttpResponseCode = /* module */[
  /* InvalidResponseCode */InvalidResponseCode,
  /* tryCreate */tryCreate,
  /* create */create
];

var UnknownHttpMethod = Caml_exceptions.create("TestSuite-Resting.UnknownHttpMethod");

exports.HttpResponseCode  = HttpResponseCode;
exports.UnknownHttpMethod = UnknownHttpMethod;
/* No side effect */
