// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var UnknownHttpMethod = Caml_exceptions.create("TestSuite-Testingbug.UnknownHttpMethod");

exports.UnknownHttpMethod = UnknownHttpMethod;
/* No side effect */
