// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Fs          = require("fs");
var List        = require("bs-platform/lib/js/list.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var JsYaml      = require("js-yaml");
var Json_decode = require("bs-json/src/Json_decode.js");

function method_() {
  return /* Get */0;
}

function headers() {
  return /* [] */0;
}

function testCase(json) {
  return /* record */[
          /* description */Json_decode.field("description", Json_decode.string, json),
          /* method */Json_decode.field("method", method_, json),
          /* url */Json_decode.field("description", Json_decode.string, json),
          /* auth : None */0,
          /* headers */Json_decode.field("headers", headers, json),
          /* expect : None */0,
          /* assertions : None */0,
          /* preRequest : None */0,
          /* postRequest : None */0
        ];
}

function dictToArray(dict, prev, key) {
  return /* :: */[
          /* tuple */[
            key,
            dict[key]
          ],
          prev
        ];
}

function environmentVariables(json) {
  var d = Json_decode.dict(Json_decode.string, json);
  return Object.keys(d).reduce((function (param, param$1) {
                return dictToArray(d, param, param$1);
              }), /* [] */0);
}

function testCases(json) {
  return Json_decode.list(testCase, json);
}

function testSuite(json) {
  return /* record */[
          /* testCases */Json_decode.field("testCases", (function (param) {
                  return Json_decode.list(testCase, param);
                }), json),
          /* environmentVariables */Json_decode.field("environmentVariables", environmentVariables, json)
        ];
}

var Decode = /* module */[
  /* method_ */method_,
  /* headers */headers,
  /* testCase */testCase,
  /* dictToArray */dictToArray,
  /* environmentVariables */environmentVariables,
  /* testCases */testCases,
  /* testSuite */testSuite
];

var file = Fs.readFileSync("testfile.yaml", "utf8");

var json = Curry._2(JsYaml.safeLoad, file, /* () */0);

var result = Json_decode.list(testCase, json);

console.log(List.hd(result)[/* description */0]);

exports.Decode = Decode;
exports.file   = file;
exports.result = result;
/* file Not a pure module */
