// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry   = require("bs-platform/lib/js/curry.js");
var Js_json = require("bs-platform/lib/js/js_json.js");
var JsYaml  = require("js-yaml");

var value = Curry._2(JsYaml.safeLoad, "test: 123", /* () */0);

var match = Js_json.decodeObject(value);

var a = match ? Object.keys(match[0]) : /* array */[];

console.log(a);

console.log(JSON.stringify(value));

exports.value = value;
exports.a     = a;
/* value Not a pure module */
